// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }















import type { Metadata } from 'next'
import { Montserrat, Open_Sans } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'

// const inter = Inter({ subsets: ['latin'] })

// const montserrat = Montserrat({
//   subsets: ['latin'],
//   variable: '--font-montserrat',
//   display: 'swap',
// })

// const openSans = Open_Sans({
//   subsets: ['latin'],
//   variable: '--font-open-sans',
//   display: 'swap',
// })

const montserrat = Montserrat({ 
  subsets: ['latin'],
  variable: '--font-montserrat',
})

const openSans = Open_Sans({ 
  subsets: ['latin'],
  variable: '--font-open-sans',
})

export const viewport = {
  width: 'device-width',
  initialScale: 1.0,
  viewportFit: 'cover',
}

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'

export const metadata: Metadata = {
  title: {
    default: 'Skilled Leadership Factory',
    template: '%s | Skilled Leadership Factory',
  },
  description: 'Virtual assistant training, tech training in Nigeria',
  keywords: [
    'leadership',
    'training',
    'virtual assistant',
    'tech training',
    'Abeokuta',
    'Ogun State',
  ],
  authors: [{ name: 'Skilled Leadership Factory' }],
  openGraph: {
    title: 'Skilled Leadership Factory',
    description: 'Virtual assistant training, tech training in Nigeria',
    url: SITE_URL,
    siteName: 'Skilled Leadership Factory',
    type: 'website',
    images: [
      {
        url: `${SITE_URL}/slf_logo.jpg`,
        width: 1200,
        height: 630,
        alt: 'Skilled Leadership Factory',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Skilled Leadership Factory',
    description: 'Virtual assistant training, tech training in Nigeria',
    images: [`${SITE_URL}/slf_logo.jpg`],
  },
  icons: {
    icon: '/favicon.ico',
    apple: '/favicon.ico',
  },
  alternates: {
    canonical: SITE_URL,
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <link rel="canonical" href={SITE_URL} />
        <script type="application/ld+json">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "Organization",
            name: 'Skilled Leadership Factory',
            url: SITE_URL,
          })}
        </script>
      </head>
      <body className={`${openSans.variable} ${montserrat.variable} font-sans`}>
        <Navbar />
        <main className="min-h-screen bg-gray-50">{children}</main>
      </body>
    </html>
  )
}